In [1]:
import geopandas as gpd
import pandas as pd
from pathlib import Path

In [2]:
# path
folder = Path('~/Documents/SIG/Otras capas venezuela/Areas_protegidas_WDPA_WDOECM_Mar2026_Public_VEN_shp').expanduser()

# merge 3 layers
abrae = gpd.GeoDataFrame(
    pd.concat([
        gpd.read_file(folder / 'WDPA_WDOECM_Mar2026_Public_VEN_shp_0'/'WDPA_WDOECM_Mar2026_Public_VEN_shp-polygons.shp'),
        gpd.read_file(folder /'WDPA_WDOECM_Mar2026_Public_VEN_shp_1'/ 'WDPA_WDOECM_Mar2026_Public_VEN_shp-polygons.shp'),
        gpd.read_file(folder /'WDPA_WDOECM_Mar2026_Public_VEN_shp_2'/ 'WDPA_WDOECM_Mar2026_Public_VEN_shp-polygons.shp'),
    ], ignore_index=True)
)

In [3]:

# exploraration
pd.set_option('display.max_columns', None)
abrae.sample(5)

,SITE_ID,SITE_PID,SITE_TYPE,NAME_ENG,NAME,DESIG,DESIG_ENG,DESIG_TYPE,IUCN_CAT,INT_CRIT,REALM,REP_M_AREA,GIS_M_AREA,REP_AREA,GIS_AREA,NO_TAKE,NO_TK_AREA,STATUS,STATUS_YR,GOV_TYPE,GOVSUBTYPE,OWN_TYPE,OWNSUBTYPE,MANG_AUTH,MANG_PLAN,VERIF,METADATAID,PRNT_ISO3,ISO3,SUPP_INFO,CONS_OBJ,INLND_WTRS,OECM_ASMT,geometry
258,555705253,555705253,PA,Utilidad Pública y de Interés Turístico Recrea...,Utilidad Pública y de Interés Turístico Recrea...,Zona de Interés Turístico (ZIT),Tourist Interest Area (ZIT),National,V,Not Applicable,Terrestrial,0.0,2.425524,310.4931,309.337030,Not Applicable,0.0,Designated,1974,Federal or national ministry or agency,Not Applicable,Multiple ownership,Not Reported,Ministerio del Poder Popular para el Turismo y...,No,State Verified,1981,VEN,VEN,Not Applicable,Not Applicable,Not Reported,Not Applicable,"POLYGON ((-64.20407 10.35677, -64.19034 10.320..."
70,20070,20070,PA,Macizo Montañoso del Turimiquire,Macizo Montañoso del Turimiquire,Zona Protectora (ZP),Protective Zone (ZP),National,VI,Not Applicable,Terrestrial,0.0,0.000000,5531.8700,5089.801317,Not Applicable,0.0,Designated,1974,Federal or national ministry or agency,Not Applicable,Multiple ownership,Not Reported,Ministerio del Poder Popular para el Ecosocial...,Si,State Verified,1981,VEN,VEN,Not Applicable,Not Applicable,Not Reported,Not Applicable,"POLYGON ((-63.51383 10.40615, -63.5099 10.4046..."
268,555705263,555705263,PA,Zona de Interés Turístico y de Utilidad Públic...,Zona de Interés Turístico y de Utilidad Públic...,Zona de Interés Turístico (ZIT),Tourist Interest Area (ZIT),National,V,Not Applicable,Terrestrial,0.0,0.000000,4.8082,4.563738,Not Applicable,0.0,Designated,1992,Federal or national ministry or agency,Not Applicable,Multiple ownership,Not Reported,Ministerio del Poder Popular para el Turismo y...,Si,State Verified,1981,VEN,VEN,Not Applicable,Not Applicable,Not Reported,Not Applicable,"POLYGON ((-63.89139 11.08532, -63.89141 11.085..."
121,30665,30665,PA,Peribeca,Peribeca,Zona de Aprovechamiento Agrícola (ZAA),Agricultural Development Zone (ZAA),National,VI,Not Applicable,Terrestrial,0.0,0.000000,3.9500,3.199716,Not Applicable,0.0,Designated,1980,Federal or national ministry or agency,Not Applicable,Multiple ownership,Not Reported,Ministerio del Poder Popular para la Agricultu...,No,State Verified,1981,VEN,VEN,Not Applicable,Not Applicable,Not Reported,Not Applicable,"POLYGON ((-72.26363 7.84747, -72.26218 7.84746..."
102,30033,30033,PA,Dr. Antonio José Uzcátegui Burguera (Sierra de...,Dr. Antonio José Uzcátegui Burguera (Sierra de...,Parque Nacional (PN),National Park (PN),National,II,Not Applicable,Terrestrial,0.0,0.000000,2015.9800,2011.135715,Not Applicable,0.0,Designated,1989,Federal or national ministry or agency,Not Applicable,State,Not Applicable,Instituto Nacional de Parques (INPARQUES),Si,State Verified,1981,VEN,VEN,Not Applicable,Not Applicable,Not Reported,Not Applicable,"POLYGON ((-71.3026 8.59527, -71.30286 8.59598,..."

In [4]:
# Extract only useful lyrs
abrae.columns
cols = ['SITE_ID','NAME_ENG','DESIG',
       'DESIG_ENG', 'IUCN_CAT','STATUS_YR', 'MANG_AUTH', 'MANG_PLAN', 'GIS_AREA','GIS_M_AREA','geometry']

In [5]:
# New subset
abrae= abrae[cols]
abrae.sample(5)

,SITE_ID,NAME_ENG,DESIG,DESIG_ENG,IUCN_CAT,STATUS_YR,MANG_AUTH,MANG_PLAN,GIS_AREA,GIS_M_AREA,geometry
91,20093,Valle del Quíbor,Reserva Nacional Hidraúlica (RNH),National Hydraulic Reserve (RNH),VI,1974,Ministerio del Poder Popular para la Agricultu...,No,625.021559,0.000000,"POLYGON ((-69.73333 10.08333, -69.45 10.08333,..."
106,30637,De la Ciudad de Coro,Zona Protectora (ZP),Protective Zone (ZP),VI,1987,Ministerio del Poder Popular para el Ecosocial...,Si,196.026367,0.000000,"POLYGON ((-69.57194 11.42365, -69.56861 11.410..."
209,145555,Parque Nacional Archipiélago Los Roques,Wetland of International Importance (Ramsar Site),Wetland of International Importance (Ramsar Site),II,1996,Instituto Nacional de Parques (INPARQUES),Si,2209.725023,2174.095987,"POLYGON ((-66.50175 11.69681, -67.00177 11.696..."
142,101086,Páramo La Laja,Área Boscosa Bajo Protección (ABBP),Forest Area Under Protection (ABBP),V,1991,Ministerio del Poder Popular para el Ecosocial...,No,22.150143,0.000000,"POLYGON ((-72.34641 7.80562, -72.34631 7.80563..."
244,555705239,Cuevas de Paraguaná,Santuario de Fauna Silvestre (SFS),Wildlife Sanctuary (SFS),III,2008,Ministerio del Poder Popular para el Ecosocial...,No,0.723479,0.180713,"MULTIPOLYGON (((-70.28752 11.79438, -70.2875 1..."

In [6]:
# Subset with only ABRAEs of interest
abrae['DESIG'].unique().tolist()
list_of_interest = ['Monumento Natural (MN)',
 'Parque Nacional (PN)', 'Reserva Nacional Hidraúlica (RNH)',
 'Zona Protectora (ZP)','Reserva Forestal (RF)', 'Área Boscosa Bajo Protección (ABBP)']

In [7]:
abrae_clean = abrae[abrae['DESIG'].isin(list_of_interest)]
abrae_clean['DESIG'].value_counts()

DESIG
Zona Protectora (ZP)                   64
Parque Nacional (PN)                   43
Área Boscosa Bajo Protección (ABBP)    43
Monumento Natural (MN)                 37
Reserva Nacional Hidraúlica (RNH)      14
Reserva Forestal (RF)                  14
Name: count, dtype: int64

In [8]:
# Reproject ABRAE layers to the same Albers Equal-Area CRS used by the land cover rasters

# Output folder
output_path = Path.cwd() / 'abraes_lyrs'
output_path.mkdir(parents=True, exist_ok=True)

ALBERS = (
    "+proj=aea +lat_1=2 +lat_2=10 +lat_0=6 +lon_0=-66 "
    "+x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs"
)

# Ensure geometries are valid before reprojection
abrae_clean = abrae_clean.copy()
abrae_clean["geometry"] = abrae_clean.geometry.make_valid()

# Reproject to Albers
abrae_albers = abrae_clean.to_crs(ALBERS)

# Output
output_albers = output_path / "abraes_by_type_albers.gpkg"


# export each type in a layer within the geopackage
for type, group in abrae_albers.groupby('DESIG'):  
    lyr_name = type.replace(' ', '_').lower()
    group.to_file(output_albers, layer=lyr_name, driver='GPKG')