In [10]:
import geopandas as gpd
import pandas as pd
from pathlib import Path

In [11]:
# path
folder = Path('~/Documents/SIG/Otras capas venezuela/Areas_protegidas_WDPA_WDOECM_Mar2026_Public_VEN_shp').expanduser()



# merge 3 layers
abrae = gpd.GeoDataFrame(
    pd.concat([
        gpd.read_file(folder / 'WDPA_WDOECM_Mar2026_Public_VEN_shp_0'/'WDPA_WDOECM_Mar2026_Public_VEN_shp-polygons.shp'),
        gpd.read_file(folder /'WDPA_WDOECM_Mar2026_Public_VEN_shp_1'/ 'WDPA_WDOECM_Mar2026_Public_VEN_shp-polygons.shp'),
        gpd.read_file(folder /'WDPA_WDOECM_Mar2026_Public_VEN_shp_2'/ 'WDPA_WDOECM_Mar2026_Public_VEN_shp-polygons.shp'),
    ], ignore_index=True)
)

In [12]:

# exploraration
pd.set_option('display.max_columns', None)
abrae.sample(5)

,SITE_ID,SITE_PID,SITE_TYPE,NAME_ENG,NAME,DESIG,DESIG_ENG,DESIG_TYPE,IUCN_CAT,INT_CRIT,REALM,REP_M_AREA,GIS_M_AREA,REP_AREA,GIS_AREA,NO_TAKE,NO_TK_AREA,STATUS,STATUS_YR,GOV_TYPE,GOVSUBTYPE,OWN_TYPE,OWNSUBTYPE,MANG_AUTH,MANG_PLAN,VERIF,METADATAID,PRNT_ISO3,ISO3,SUPP_INFO,CONS_OBJ,INLND_WTRS,OECM_ASMT,geometry
272,555705267,555705267,PA,Subcuenca del Río Momboy,Subcuenca del Río Momboy,Zona Protectora (ZP),Protective Zone (ZP),National,VI,Not Applicable,Terrestrial,0.00,0.000000,125.54,125.042304,Not Applicable,0.0,Designated,1993,Federal or national ministry or agency,Not Applicable,Multiple ownership,Not Reported,Ministerio del Poder Popular para el Ecosocial...,No,State Verified,1981,VEN,VEN,Not Applicable,Not Applicable,Not Reported,Not Applicable,"POLYGON ((-70.7057 9.03904, -70.70634 9.03846,..."
91,20093,20093,PA,Valle del Quíbor,Valle del Quíbor,Reserva Nacional Hidraúlica (RNH),National Hydraulic Reserve (RNH),National,VI,Not Applicable,Terrestrial,0.00,0.000000,720.00,625.021559,Not Applicable,0.0,Designated,1974,Collaborative governance,Not Reported,Multiple ownership,Not Reported,Ministerio del Poder Popular para la Agricultu...,No,State Verified,1981,VEN,VEN,Not Applicable,Not Applicable,Not Reported,Not Applicable,"POLYGON ((-69.73333 10.08333, -69.45 10.08333,..."
45,10776,10776,PA,Del Área Metropolitana de Caracas,Del Área Metropolitana de Caracas,Zona Protectora (ZP),Protective Zone (ZP),National,VI,Not Applicable,Terrestrial,0.00,0.000000,843.00,669.919125,Not Applicable,0.0,Designated,1972,Collaborative governance,Not Reported,Multiple ownership,Not Reported,Ministerio del Poder Popular para la Agricultu...,Si,State Verified,1981,VEN,VEN,Not Applicable,Not Applicable,Not Reported,Not Applicable,"MULTIPOLYGON (((-66.66284 10.50119, -66.66191 ..."
17,331,331,PA,Laguna de Tacarigua,Laguna de Tacarigua,Parque Nacional (PN),National Park (PN),National,II,Not Applicable,Coastal,205.72,262.010201,399.66,401.600634,Not Reported,0.0,Designated,1974,Federal or national ministry or agency,Not Applicable,State,Not Applicable,Instituto Nacional de Parques (INPARQUES),Si,State Verified,1981,VEN,VEN,Not Applicable,Not Applicable,Not Reported,Not Applicable,"POLYGON ((-65.76637 10.18756, -65.8669 10.2173..."
86,20088,20088,PA,Zona Sur Lago de Maracaibo,Zona Sur Lago de Maracaibo,Reserva Nacional Hidraúlica (RNH),National Hydraulic Reserve (RNH),National,VI,Not Applicable,Terrestrial,0.00,5.031730,6180.00,8999.482718,Not Applicable,0.0,Designated,1974,Collaborative governance,Not Reported,Multiple ownership,Not Reported,Ministerio del Poder Popular para la Agricultu...,No,State Verified,1981,VEN,VEN,Not Applicable,Not Applicable,Not Reported,Not Applicable,"POLYGON ((-71.71874 9.38351, -71.71869 9.38322..."

In [ ]:
# Extract only useful lyrs
abrae.columns
cols = ['SITE_ID','NAME_ENG','DESIG',
       'DESIG_ENG', 'IUCN_CAT','STATUS_YR', 'MANG_AUTH', 'MANG_PLAN', 'GIS_AREA','GIS_M_AREA','geometry']

In [ ]:
# New subset
abrae= abrae[cols]
abrae.sample(5)

,SITE_ID,NAME_ENG,DESIG,DESIG_ENG,IUCN_CAT,STATUS_YR,MANG_AUTH,MANG_PLAN,GIS_AREA,GIS_M_AREA,geometry
269,555705264,"Dependencias Federales: Isla La Tortuga, Las T...",Zona de Interés Turístico (ZIT),Tourist Interest Area (ZIT),V,1974,Ministerio del Poder Popular para el Turismo y...,Si,872.728205,737.661279,"POLYGON ((-65.15634 10.75266, -65.4982 10.7500..."
94,30023,Ciénagas de Juan Manuel,Parque Nacional (PN),National Park (PN),II,1991,Instituto Nacional de Parques (INPARQUES),No,1882.040924,212.031467,"MULTIPOLYGON (((-71.7118 9.39355, -71.70921 9...."
194,101144,Cerro Guanay,Monumento Natural (MN),Natural Monument (MN),III,1990,Instituto Nacional de Parques (INPARQUES),No,353.820155,0.000000,"POLYGON ((-66.33515 5.74674, -66.46849 5.74674..."
25,339,Estero de Chiriguare,Refugio de Fauna Silvestre (RFS),Wildlife Refuge (RFS),IV,1974,Ministerio del Poder Popular para el Ecosocial...,No,322.764959,0.000000,"POLYGON ((-68.77568 8.60494, -68.77533 8.60433..."
8,318,Perijá,Parque Nacional (PN),National Park (PN),II,1978,Instituto Nacional de Parques (INPARQUES),Si,2897.306104,0.000000,"POLYGON ((-72.9819 9.96983, -72.98169 9.97043,..."

In [ ]:
# Subset with only ABRAEs of interest
abrae['DESIG'].unique().tolist()
list_of_interest = ['Monumento Natural (MN)',
 'Parque Nacional (PN)', 'Reserva Nacional Hidraúlica (RNH)',
 'Zona Protectora (ZP)','Reserva Forestal (RF)', 'Área Boscosa Bajo Protección (ABBP)']

In [16]:
abrae_clean = abrae[abrae['DESIG'].isin(list_of_interest)]
abrae_clean['DESIG'].value_counts()

DESIG
Zona Protectora (ZP)                   64
Parque Nacional (PN)                   43
Área Boscosa Bajo Protección (ABBP)    43
Monumento Natural (MN)                 37
Reserva Nacional Hidraúlica (RNH)      14
Reserva Forestal (RF)                  14
Name: count, dtype: int64

In [ ]:
# Output folder
output_path = Path.cwd() / 'abraes_lyrs'
output_path.mkdir(parents=True, exist_ok=True)
output = output_path / 'abraes_by_type.gpkg'


# export each type in a layer within the geopackage
for type, group in abrae_clean.groupby('DESIG'):  
    lyr_name = type.replace(' ', '_').lower()
    group.to_file(output, layer=lyr_name, driver='GPKG')